version: "3.7"

services:
  web:
    build: .
    command: uvicorn app.main:app --host 0.0.0.0 --port 8080
    volumes:
      - .:/app
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://meahome_postgres_user:SXkSicAdQfG40H06i5bkwVb3pHWg37kp@dpg-cq9vj1lds78s739k1u10-a.oregon-postgres.render.com/meahome_postgres

  db:
    image: postgres:12.0-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=ameazza
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=nudges
    expose:
      - 5432

volumes:
  postgres_data:
